project:
  type: website
website:
  title: "Axel's Personal Website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: About
        href: about.qmd
output-dir: docs
format:
  html:
    css: styles.css



