project:
  type: website
  output-dir: docs
website:
  title: "Axel's Website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Hobbies
        href: hobbies.qmd
      - text: About
        href: about.qmd
output-dir: docs
format:
  html:
    css: styles.css


